/*
 *  ACSDrawDefs.h
 *  ACSDraw
 *
 *  Created by Alan Smith on Sat Feb 02 2002.
 *  Copyright (c) 2001 __MyCompanyName__. All rights reserved.
 *
 */

enum
   {
	MENU_DEF_EXPORT_SVG=151,
	MENU_DEF_CUT=230,
	MENU_DEF_COPY=240,
	MENU_DEF_PASTE=250,
	MENU_DEF_DUPLICATE=260,
	MENU_DEF_CLEAR=270,
	MENU_DEF_SELECT_ALL=280,
	MENU_DEF_SMART_GUIDES=330,
	MENU_DEF_BRING_TO_FRONT=401,
	MENU_DEF_SEND_TO_BACK,
	MENU_DEF_BRING_FORWARD,
	MENU_DEF_SEND_BACKWARD,
	MENU_DEF_ALIGN_LEFT_EDGES,
	MENU_DEF_ALIGN_RIGHT_EDGES,
	MENU_DEF_ALIGN_TOP_EDGES,
	MENU_DEF_ALIGN_BOTTOM_EDGES,
	MENU_DEF_ALIGN_VERTICAL_CENTRES,
	MENU_DEF_ALIGN_HORIZONTAL_CENTRES,
	MENU_DEF_CONVERT_TO_PATH=411,

   };

